### ISSUE TITLE
Format README.md

### ISSUE THREAD

**Issue by emmalearnscode** [emmalearnscode/guide-to-HF#1]
The readme.md file should be formatted so that it's more pleasing to look at.

1. Add heading
2. Add link to CONTRIBUTING.md file
3. Add link to twitter handle.

**Comment by patricktrp** [comment]
you can assign this issue to me!

**Comment by emmalearnscode** [comment]
Absolutely, good luck and let me know if you need any help!

**Comment by patricktrp** [comment]
I already opened a PR :D

**Comment by sunnythepatel** [comment]
Updated Readme as requested

**Comment by emmalearnscode** [comment]
Hi @sunnythepatel this issue is already assigned to @patricktrp so please wait with your submission to avoid duplicate work

**Comment by sunnythepatel** [comment]
Hi @emmalearnscode  ok sure
