### ISSUE TITLE
Add information about setting upstream remotes for returning contributors

### ISSUE THREAD

**Issue by JacksonBates** [emmalearnscode/guide-to-HF#11]
_These details can be added to the website and to the contributing.md, potentially as separate PRs ;)_

When a user intends to make multiple contributions to a repository it is very easy for them to get their forked repo out of sync with this original repo.

To overcome this, they have to set their upstream remote as this repository.

From the command line (UNIX based, I'm afraid I'm not too familiar with Windows these days) they can follow these instructions:

```
 git remote -v
```
This will list the current remotes. It should show something like this:
```
origin git@github.com:JacksonBates/guide-to-HF.git (fetch)
origin git@github.com:JacksonBates/guide-to-HF.git (push)
```
Then they can do this:
```
git remote add upstream git@github.com:emmalearnscode/guide-to-HF.git
```
Now if they do `git remote -v` again they should see:
```
origin	git@github.com:JacksonBates/guide-to-HF.git (fetch)
origin	git@github.com:JacksonBates/guide-to-HF.git (push)
upstream	git@github.com:emmalearnscode/guide-to-HF.git (fetch)
upstream	git@github.com:emmalearnscode/guide-to-HF.git (push)
```

Now, before they do new work on the repo, they should pull any updates in from this original repo like this:
```
git pull upstream master
```
This takes all the changes on this repo and applies them to the fork to keep them in sync.

If anyone needs more detail to understand this, feel free to @ mention me :)

**Comment by jebitok-dev** [comment]
I could add the contribution guidelines/steps

**Comment by sunnythepatel** [comment]
Hi @JacksonBates  & @emmalearnscode  I have updated the contribution.md as mentioned

**Comment by emmalearnscode** [comment]
@sunnythepatel please don’t submit pull requests unless you’ve been assigned. I understand you may be eager but you need to wait to be assigned before submitting pull requests.

**Comment by sunnythepatel** [comment]
Ok sure. Can I do this @emmalearnscode I have already completed this one?

**Comment by JacksonBates** [comment]
This issue actually represents 2 pieces of work. @jebitok-dev might still like to do the website changes if @sunnythepatel only did the contributing.md?

Just a thought :)

**Comment by emmalearnscode** [comment]
Good idea @JacksonBates 
Contributing.md assigned to @sunnythepatel 

Changes to website assigned to @jebitok-dev  Add it to the fork the repo page for now with heading ‘Keeping your forked repo up to date’
