### ISSUE TITLE
Top nav hover 'jitters'

### ISSUE THREAD

**Issue by JacksonBates** [emmalearnscode/guide-to-HF#12]
Tiny improvement suggestion for the site:

This should be a reasonably easy first issue, that requires a little CSS knowledge.

## Replicate issue
Hover over the top nav menu items. Notice how things jump around a little.

## Cause / clues
Some decorative properties change the size of the box-model values (margin, border, padding, content). 
There are other decorative properties that do not (box shadow, background-color).

It should be relative simple to reimplement the hover effect without having it jump around on the nav bar.

**Comment by guidimas** [comment]
Hi, I can work on this one. May you assign it to me? Thank you.

**Comment by JacksonBates** [comment]
I can't assign, it's up to @emmalearnscode, who is in a different timezone to me and probably asleep :)

**Comment by emmalearnscode** [comment]
Have fun working on it @guidimas let me know if you need help
