### ISSUE TITLE
Add styles to media queries

### ISSUE THREAD

**Issue by emmalearnscode** [emmalearnscode/guide-to-HF#17]
On screens smaller than 600px add a media query for the p tag so that it has 5px padding on the right and left sides.

**Comment by SahilKumar7** [comment]
I would like to work on this

**Comment by emmalearnscode** [comment]
Please wait to be assigned before submitting your pr in the future 😊

**Comment by coolpythoncodes** [comment]
Is this issue is open. I am looking at contributing.

**Comment by emmalearnscode** [comment]
Sahil is already working on it but for some reason I can't assign it to him. Keep your eye out for more issues coming over the coming days.

**Comment by coolpythoncodes** [comment]
Okay, While I am waiting, I asked for permission to contribute to your calculator project.

I want to add speech recognition functionality.
