### ISSUE TITLE
Top navigation look & feel on mobile devices

### ISSUE THREAD

**Issue by guidimas** [emmalearnscode/guide-to-HF#24]
Little improvement suggestion:

It requires a little CSS knowledge.

## Replicate issue

In mobile devices (or simulating), open the top navigation menu;
The active menu item has a weird border radius and;
On hover / When active, it overlaps the other menu items.

## Cause / clues

The border radius issue is caused by the CSS 'border-radius' property, since it sets only the bottom radius.

About the overlapping, my guess is that the display 'block' set to the nav when the menu is open and/or the 'margin' set to the 'li' items, is causing this overlapping.

**Comment by emmalearnscode** [comment]
Issues to fix on screens smaller than 730px (the media query exists already):

-make margin 0px on the nav li
-make nav a display: block
-change padding to 1em all around on nav a
-remove border-bottom-radius's from the nav-active class

**Comment by frankremmy** [comment]
Hi @emmalearnscode. I can work this out. Kindly assign it to me.

**Comment by frankremmy** [comment]
@emmalearnscode Seen. I'm on it now. Will keep a close communication on Discord.

**Comment by frankremmy** [comment]
Kindly review and merge if deem fit.
