### ISSUE TITLE
Title font size on small mobile screens

### ISSUE THREAD

**Issue by cat-street** [emmalearnscode/guide-to-HF#25]
On 320px screen resolution the "Hacktoberfest" word isn't fitting in a screen a bit in 3rem size.
Also, some side paddings would be good at mobile resoluitons =)
![Снимок](https://user-images.githubusercontent.com/2076436/94810808-3114fb80-03fd-11eb-978a-c698cf42bb72.PNG)

**Comment by sumitgsh** [comment]
@cat-street can u assign me the issue..I would love to work on it

**Comment by emmalearnscode** [comment]
Hi @cat-street is this something you’d like to fix since you raised the issue? Someone is already working on side padding for the main content So just the header size needs adjusting

**Comment by cat-street** [comment]
@emmalearnscode yes, I'd like to contribute =)
