### ISSUE TITLE
Add media query for cards on index.html page

### ISSUE THREAD

**Issue by emmalearnscode** [emmalearnscode/guide-to-HF#28]
On screens less than 440px the cards (under section .Experiences on the index.html page) are one column wide but they have quite a lot of white space around them.

1. Add a media query for screens smaller than 440px.
2. Increase the max-width of the card to 300px
3. Reduce margin from 40px 5px to 10px 0

**Comment by danny-don** [comment]
Hello, can I have this issue please?

**Comment by emmalearnscode** [comment]
Sure, have fun!

**Comment by Adegitetaiwo** [comment]
hi, can i be assigned to this issue please?
