### ISSUE TITLE
What's the process for adding a link to 'my experience' to the main page? 

### ISSUE THREAD

**Issue by dwjohnston** [emmalearnscode/guide-to-HF#37]
In the contributors guide you've said to add a 'yourname.html' and css to the experiences folder. 

But if a user/developer wants to see a list of their experiences on the main page, how would they see that? Do you add that manually and they  need to wait to see that once the PR is approved?

**Comment by emmalearnscode** [comment]
It's also stated in the contributing.md file that I will add it after the PR is accepted

**Comment by shrutikdev** [comment]
Hello @emmalearnscode , can I contribute to this issue?
