### ISSUE TITLE
Hamburger navigation

### ISSUE THREAD

**Issue by emmalearnscode** [emmalearnscode/guide-to-HF#4]
At the moment the current navigation styling breaks at screen sizes smaller than 730px.

Please add a hamburger menu that appears at screen sizes less than 730px.

The navigation links should drop down when the hamburger is clicked on and disappear on a second click.

Add scripts to scripts.js and make a section at the bottom of the CSS file marked /*Media Queries*/

**Comment by alabo-excel** [comment]
Hello @emmalearnscode i will love to work on your project.
Would you please assign it to me?
thank you in advance.

**Comment by emmalearnscode** [comment]
Sure thing @alabo-excel Good luck and let me know if you have any problems.

**Comment by alabo-excel** [comment]
yes i do but your dm on twitteer is not open

**Comment by alabo-excel** [comment]
![hacktoberfest digitalocean com_profile(Laptop with MDPI screen)](https://user-images.githubusercontent.com/66995707/94732443-23874500-031b-11eb-880d-8b33791ee5df.png)

i have an invalid and ineligible repository.
Please how can i fix that??

**Comment by emmalearnscode** [comment]
No, you don't. That's just the legend telling you what the symbols beside the pull request mean. If you look beside the PR you should have a pending symbol which will become a red tick in 7 days when they've checked it wasn't invalid

**Comment by alabo-excel** [comment]
okay thank you very much
