### ISSUE TITLE
Change hamburger menu icon

### ISSUE THREAD

**Issue by emmalearnscode** [emmalearnscode/guide-to-HF#50]
I could like the hamburger menu changing to a standard 3 bar instead of the inverted version it is now.

Example : [https://www.google.com/url?sa=i&url=https%3A%2F%2Fcreativemms.com%2Fblog%2Fwhy-the-hamburger-navigation-icon-is-dead%2F&psig=AOvVaw3cZPoniKYtmIF8s8almt-M&ust=1601815287021000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCPCD-o25mOwCFQAAAAAdAAAAABAD]

**Comment by matheuscr30** [comment]
Can u assign this to me?

**Comment by emmalearnscode** [comment]
Sure!

**Comment by sumitgsh** [comment]
@emmalearnscode is the assigned task done?

**Comment by emmalearnscode** [comment]
@sumitgsh It is already assigned

**Comment by matheuscr30** [comment]
@sumitgsh You can do it, some unexpected events happened here and I'll not be able to do

**Comment by emmalearnscode** [comment]
Ok, thanks for letting us know @matheuscr30 I'll reassign it

**Comment by npawankr1** [comment]
very easy for me @emmalearnscode

**Comment by emmalearnscode** [comment]
It's already assigned @npawankr1 but you can be on the waiting list incase the current assignee changes their mind.

**Comment by LeonardoZanotti** [comment]
I'm sorry, i did think that the assigned person dont wanted more the task

**Comment by NinjaMandy** [comment]
you can assign it to me , i'll be on waiting list for this.
