### ISSUE TITLE
Profile Image doesn't show for Experience 14

### ISSUE THREAD

**Issue by frankremmy** [emmalearnscode/guide-to-HF#65]
The profile photo for Experience 14 (Shubham Arora) doesn't work or is broken. 

![Screenshot_20201005-073118](https://user-images.githubusercontent.com/37175426/95047330-c6eea600-06dd-11eb-9903-41a519abc593.png)

Kindly visit https://emmalearnscode.github.io/guide-to-HF/experiences/shubham-arora.html to confirm. 

More so, the experience directory https://github.com/emmalearnscode/guide-to-HF/tree/master/experiences doesn't look well arranged. Maybe I can sort it by file type (eg. html, css) or by experience (eg name of the contributor with their files in it).

**Comment by amoghrajesh** [comment]
@frankremmy I confirm that the profile pic is not shown due to him using a local file path.

**Comment by emmalearnscode** [comment]
Yeah, he never uploaded a profile pic but I just accepted the Pr anyway. 

The experience directory is alphabetically sorted on my computer which works well for me so I'm not looking for changes right now.  I think Github muddled up the order when uploading so they look unordered.
