### ISSUE TITLE
change username info on fork.html

### ISSUE THREAD

**Issue by JacksonBates** [emmalearnscode/guide-to-HF#67]
Point 8 on the fork document shows that `git remote -v` will output _my_ github fork as the origin repo...this is obviously only true for me 😄

It might make more sense to replace references to `JacksonBates` on the page with `<username>`

Very easy issue :)

**Comment by emmalearnscode** [comment]
Good point, sorry @JacksonBates I didn't catch that! Also on the contributing.md file which got updated with the same info

**Comment by jebitok-dev** [comment]
I could take up this didn't really remember that part

**Comment by emmalearnscode** [comment]
Thanks @jebitok-dev

**Comment by TharinduRewatha** [comment]
Can I do this?
