### ISSUE TITLE
Change to use CSS custom properties (variables)

### ISSUE THREAD

**Issue by emmalearnscode** [emmalearnscode/guide-to-HF#7]
The current styles.css file uses normal colour and font properties throughout the CSS file like so:

dark red: #9C4668
pink: #ff8ae2
blue: #93c2db
darkblue: #072540

font-family: 'Inter', sans-serif;
font-family: 'Nunito', sans-serif;

Instead I would like custom CSS properties at the top of the file and the hex codes and fonts replaced throughout the CSS file with custom properties. 

Name the properties as follows at the top of the file:
--bg-color: #072540; //dark blue
--bg-color-lt: #ffffff; //white
--text-color-lt: #ffffff; //white
--text-color-dk: #072540; //dark blue
--highlight-lt: #ff8ae2; // light pink
--highlight-dk: #9C4668; //dark pink

--font-header: 'Inter', sans-serif;
--font-normal: 'Nunito', sans-serif;

then change them in the corresponding places throughout the CSS file by using --var(name-of-property)

**Comment by arpancodes** [comment]
Hello @emmalearnscode I am searching for projects and issue for my very first hacktoberfest contributions and this looks very perfect for me... can you please assign it to me 😄 
Thanks in advance!

**Comment by emmalearnscode** [comment]
Sure, I assigned you. Good luck and let me know if you need any help.

**Comment by TheCoderNikhil** [comment]
Hello @emmalearnscode I am searching for projects and issue for my very first hacktoberfest contributions and this looks very perfect for me... can you please assign it to me 😄
Thanks in advance!

**Comment by harshguptahg007** [comment]
I also wanted to work on the same thing. I am doing my first open source contributions. Can you assign me this issue as well?

**Comment by emmalearnscode** [comment]
Hi @harshguptahg007 It doesn't make sense to assign you to the same issue as it will be pointless work. But keep an eye on my repo because I have more issues I will be posting over the coming days mostly to do with changing CSS.

**Comment by harshguptahg007** [comment]
Ok. No problem. Thanks for informing @emmalearnscode

**Comment by chaitanya4vedi** [comment]
@emmalearnscode Can we use Bootstrap in this project to make it more responsive and mobile friendly. I have some experience in Bootstrap. Also this project seems to be in a early stage so I think it's the right time we go with it, if you like.

**Comment by emmalearnscode** [comment]
@chaitanya4vedi If you choose to make your own html and css file about your Hacktoberfest tips and tricks for other newbies to be added to the experiences section then you are free to use bootstrap if you wish. I won't be adding bootstrap to the main site as I'd rather use flexbox and grid. Most of the site is already responsive and the bits that are not will be listed as issues over the coming days.

**Comment by chaitanya4vedi** [comment]
> @chaitanya4vedi If you choose to make your own html and css file about your Hacktoberfest tips and tricks for other newbies to be added to the experiences section then you are free to use bootstrap if you wish. I won't be adding bootstrap to the main site as I'd rather use flexbox and grid. Most of the site is already responsive and the bits that are not will be listed as issues over the coming days.

Ok. Thanks

**Comment by sakshiranipapamummy** [comment]
Hello @emmalearnscode I am searching for projects and issue for my very first hacktoberfest contributions and this looks very perfect for me... can you please assign it to me 😄
Thanks in advance!

**Comment by rudratalur** [comment]
Hello @emmalearnscode I'm doing my first Hactober contribution. Can u pease assign this issue to me.
Thanks!

**Comment by emmalearnscode** [comment]
@rudratalur This issue is closed because it's already been completed.
